# SwiftLint Configuration for Goose GUI

# Paths to include
included:
  - Goose

# Paths to exclude
excluded:
  - .build
  - Package.swift
  - Goose/GooseTests
  - Goose/GooseUITests

# Rule configuration
disabled_rules:
  - trailing_whitespace # Conflicts with Xcode auto-formatting
  - todo # We use TODO comments for tracking
  - fixme # We use FIXME comments for tracking

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule parameters
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

nesting:
  type_level: 2
  function_level: 3

cyclomatic_complexity:
  warning: 10
  error: 20

# Custom rules
custom_rules:
  mark_comment_spacing:
    name: "MARK comment spacing"
    regex: '\/\/MARK:|\/\/ MARK: -[^\s]|\/\/ MARK:[^\s-]'
    message: "Use format: // MARK: - Section Name or // MARK: Section Name"
    severity: warning
    
  empty_line_after_guard:
    name: "Empty line after guard"
    regex: 'guard[^\n]*\n[^\n]*return[^\n]*\n(?![^\n]*\n)'
    message: "Add empty line after guard statement"
    severity: warning
    
  space_after_comment:
    name: "Space after comment"
    regex: '\/\/[^\s\/]'
    message: "Add space after //"
    severity: warning

reporter: "xcode" # or "json", "csv", "html"
